# Generated by Django 5.2.13 on 2026-05-04 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("tipoDeAtividade", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "dificuldade",
                    models.CharField(
                        choices=[
                            ("facil", "Fácil"),
                            ("medio", "Médio"),
                            ("dificil", "Difícil"),
                        ],
                        default="medio",
                        max_length=10,
                    ),
                ),
                ("concluida", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atividades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
